spring:
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: root
    url: jdbc:p6spy:mysql://localhost:3306/books?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6378
    password: root
    database: 0

mybatis-plus:
  configuration:
    #    打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    二级缓存
    cache-enabled: true
  #    映射mapper文件
  mapper-locations: classpath:mapper/*.xml
  #  映射实体类别名
  type-aliases-package:
server:
  port: 8089
